### ISSUE TITLE
Does not run webpack loader on files imported from node modules

### ISSUE THREAD

**Issue by joefiorini** [istarkov/babel-plugin-webpack-loaders#116]
I'm trying to use react-toolbox in a project with `babel-plugin-webpack-loaders` for server-side rendering. react-toolbox imports raw Sass templates, so I was expecting this plugin to process them via webpack just like everything else.

I noticed that if I import one of the Sass templates directly in my code, it does get processed by the webpack loaders from the plugin. However if I let react-toolbox handle the import (which is the only way to import the components anyway), it doesn't run them through the Sass loader.

[Here's a simple repo to reproduce](https://github.com/joefiorini/babel-plugin-webpack-loaders-failing-example) both failing and working examples (run `node fail` or `node pass`).

**Comment by istarkov** [comment]
From babel docs: By default all requires to node_modules will be ignored.
You can override this by passing an ignore regex.
And as it is a babel plugin, this is expected behavior. Please read babel
docs to find babel option you need. (Im on mobile now, so cant give refs,
as it takes too long to find and copy paste something)
