### ISSUE TITLE
Use loader-runnner instead of exec

### ISSUE THREAD

**Issue by sheerun** [istarkov/babel-plugin-webpack-loaders#175]
exec is extrmely slow (it takes at least a second to process each .scss import when using this plugin.. could you consider using https://github.com/webpack/loader-runner instead?

**Comment by istarkov** [comment]
`exec` is used because it's the only way I know how to make asynchronous call to be synchronous.
The problem that `babel` is fully synchronous, so you can't use async calls inside plugins.

There were fork of this library which used https://github.com/laverdet/node-fibers or similar idea but I don't remember where. 

Also links:
https://github.com/istarkov/babel-plugin-webpack-loaders/issues/43#issuecomment-191405898
https://github.com/istarkov/babel-plugin-webpack-loaders/issues/34#issuecomment-186243618

**Comment by sheerun** [comment]
fair enough.. disappointing, though
