### ISSUE TITLE
Doesn't work with AVA tests in separate processes

### ISSUE THREAD

**Issue by jedrichards** [istarkov/babel-plugin-webpack-loaders#41]
I think this issue has already been noted here https://github.com/istarkov/babel-plugin-webpack-loaders/issues/4#issuecomment-169946455 but thought it would be worth making a dedicated issue, since it looks like no solution has been found?

The [ava](https://github.com/sindresorhus/ava) test runner runs each file under test in a new process, so I think this has the effect of adjusting the `pwd` to the folder of the current file and breaking this plugins ability to find the webpack config.

So a babel config that looks like,

```json
{
  "presets": ["es2015"],
  "env": {
    "AVA": {
      "plugins": [
        [
          "babel-plugin-webpack-loaders",
          {
            "config": "./webpack.config.ava.js",
            "verbose": false
          }
        ]
      ]
    }
  }
}
```

breaks with an error,

```
Cannot find module '/Users/jed/work/project/components/text-control/webpack.config.ava.js'
```

If I change the config to the below it works perfectly, but obviously the absolute filepath is no good on a shared project ...

```json
{
  "presets": ["es2015"],
  "env": {
    "AVA": {
      "plugins": [
        [
          "babel-plugin-webpack-loaders",
          {
            "config": "/Users/jed/work/project/webpack.config.ava.js",
            "verbose": false
          }
        ]
      ]
    }
  }
}
```

Any body got any ideas? I would be happy to try and prepare a PR ... but not sure what approach to take ...

**Comment by istarkov** [comment]
I can't get the idea of why `ava` changes process.cwd for tests. I never had those problem with `path.join(__dirname` as in `ava` documentation.

But as we talk not about `ava`, the problem is how to convert relative path in `.babelrc` to abs path.
[process.cwd()](https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/src/plugin.js#L182) is not a good solution but I have no other simple enough. 

As a variant use some magic env variable like `WEBPACK_CONFIG_ROOT` and resolve path at 182 line via `WEBPACK_CONFIG_ROOT` if `process.env.WEBPACK_CONFIG_ROOT` exists.

So you could run test as

```
WEBPACK_CONFIG_ROOT=`pwd` .. bla bla... ava blabla 
```

Or allow `$vars` in plugin `config` section, and set any var you like
```
"plugins": [
        [
          "babel-plugin-webpack-loaders",
          {
            "config": "${SOMEVAR}/project/webpack.config.ava.js",
            "verbose": false
          }
        ]
      ]
```

**Comment by jedrichards** [comment]
Something like that? https://github.com/istarkov/babel-plugin-webpack-loaders/pull/42

It wasn't clear to me how to add specific tests for it, without duplicating a lot of testing structure.

I could add a section to the readme too, similar to the Caching Issues https://github.com/istarkov/babel-plugin-webpack-loaders#caching-issues section you have already?

**Comment by istarkov** [comment]
https://github.com/istarkov/babel-plugin-webpack-loaders/pull/42#discussion_r54756620

It's easy to test, just add additional test config and check that path to config is resolved with your variable,

**Comment by jedrichards** [comment]
Fixed and closed via: https://github.com/istarkov/babel-plugin-webpack-loaders/pull/42
Info in the readme here: https://github.com/istarkov/babel-plugin-webpack-loaders#dynamic-config-path

Ty help @istarkov :tada:

**Comment by sindresorhus** [comment]
This will soon be fixed in AVA core and the workaround will not be needed anymore. We decided to reverse the decision to make CWD be the test file and instead it will be the directory of your package.json. See: https://github.com/avajs/ava/issues/32

We could use some help with https://github.com/avajs/ava-codemods/issues/19 so we can get the change into a release.
