### ISSUE TITLE
Error on Import external css library

### ISSUE THREAD

**Issue by mysticmana** [istarkov/babel-plugin-webpack-loaders#7]
Based on [minimal example](https://github.com/istarkov/minimal-example-for-babel-plugin-webpack-loaders),  I npm install normalize.css and added import "normalize.css/normalize.css" to example.js.
I am getting following error on npm run start:
`You can't import file normalize.css/normalize.css to a module scope.`
Any idea how to fix this?

**Comment by istarkov** [comment]
The problem is here https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/src/plugin.js#L100
For now plugin does not supports `imports` which are resolved using via `node_modules`.
I want to say that it just supports relative pathes.
To avoid this, we need to move to this package (or to `require.resolve`) https://github.com/substack/node-resolve to resolve file pathes.

So instead of `path.resolve` there is need to use node like resolve, 
look also at this issue https://github.com/istarkov/babel-plugin-webpack-loaders/issues/4 (resolve must be able to intercept names other than `node_modules`)

**Comment by nkbt** [comment]
`resolve.alias` webpack config might help too https://webpack.github.io/docs/configuration.html#resolve-alias

**Comment by istarkov** [comment]
Fixed at #9 #11 
example:
https://github.com/istarkov/babel-plugin-webpack-loaders/blob/master/examples/myCoolLibrary/myCoolLibrary.js#L6
